# Generated by Django 5.0.9 on 2026-08-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField(verbose_name='pH du sol')),
                ('azote', models.FloatField(verbose_name='azote N (mg/kg)')),
                ('phosphore', models.FloatField(verbose_name='phosphore P (mg/kg)')),
                ('potassium', models.FloatField(verbose_name='potassium K (mg/kg)')),
                ('temperature', models.FloatField(verbose_name='temperature (degres C)')),
                ('humidite', models.FloatField(verbose_name='humidite relative (%)')),
                ('pluviometrie', models.FloatField(verbose_name='pluviometrie (mm/an)')),
                ('matiere_organique', models.FloatField(blank=True, null=True, verbose_name='matiere organique (%)')),
                ('argile', models.FloatField(blank=True, null=True, verbose_name='argile (%)')),
                ('limon', models.FloatField(blank=True, null=True, verbose_name='limon (%)')),
                ('sable', models.FloatField(blank=True, null=True, verbose_name='sable (%)')),
                ('indice_confiance', models.FloatField(blank=True, null=True)),
                ('importances_variables', models.JSONField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminee'), ('erreur', 'Erreur')], default='en_attente', max_length=15)),
                ('validee', models.BooleanField(default=False)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'analyse de sol',
                'verbose_name_plural': 'analyses de sol',
                'ordering': ['-date_analyse'],
            },
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('rang', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'recommandation de culture',
                'verbose_name_plural': 'recommandations de cultures',
                'ordering': ['rang'],
            },
        ),
    ]
