# Generated by Django 5.0.9 on 2026-08-29 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyses', '0001_initial'),
        ('parcelles', '0001_initial'),
        ('referentiel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='operateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analyses_realisees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyse',
            name='parcelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='parcelles.parcelle'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='type_sol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='referentiel.typesol'),
        ),
        migrations.AddField(
            model_name='recommandation',
            name='analyse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='analyses.analyse'),
        ),
        migrations.AddField(
            model_name='recommandation',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referentiel.culture'),
        ),
        migrations.AlterUniqueTogether(
            name='recommandation',
            unique_together={('analyse', 'culture')},
        ),
    ]
