# Generated by Django 5.0.9 on 2026-08-29 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_initial'),
        ('referentiel', '0002_culture_code_culture_couleur_hex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyse',
            name='indice_confiance',
        ),
        migrations.AddField(
            model_name='analyse',
            name='confiance_culture',
            field=models.FloatField(blank=True, null=True, verbose_name='indice de confiance (culture)'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='confiance_sol',
            field=models.FloatField(blank=True, null=True, verbose_name='indice de confiance (type de sol)'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='culture_predite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyses_predites', to='referentiel.culture', verbose_name='culture recommandee par le modele'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='photo_sol',
            field=models.ImageField(blank=True, null=True, upload_to='analyses/photos/', verbose_name='photo du sol'),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='type_sol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='referentiel.typesol', verbose_name='type de sol identifie'),
        ),
    ]
