# Generated by Django 5.0.9 on 2026-08-30 08:14

import analyses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_remove_analyse_indice_confiance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='photo_sol',
            field=models.ImageField(blank=True, null=True, upload_to=analyses.models.chemin_photo_sol, verbose_name='photo du sol'),
        ),
    ]
