# Generated by Django 5.0.9 on 2026-08-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.PositiveIntegerField(unique=True)),
                ('algorithme', models.CharField(default='RandomForestClassifier', max_length=100)),
                ('exactitude', models.FloatField()),
                ('precision_moy', models.FloatField()),
                ('rappel_moy', models.FloatField()),
                ('score_f1', models.FloatField()),
                ('chemin_fichier', models.CharField(max_length=255)),
                ('est_active', models.BooleanField(default=False)),
                ('date_entrainement', models.DateTimeField(auto_now_add=True)),
                ('nb_observations_entrainement', models.PositiveIntegerField(default=0)),
                ('hyperparametres', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'version du modele',
                'verbose_name_plural': 'versions du modele',
                'ordering': ['-numero_version'],
            },
        ),
    ]
