# Generated by Django 5.0.9 on 2026-08-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='code')),
                ('libelle', models.CharField(max_length=100, verbose_name='libelle')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('ph_min', models.FloatField(verbose_name='pH minimal observe')),
                ('ph_max', models.FloatField(verbose_name='pH maximal observe')),
                ('couleur_hex', models.CharField(default='#3388ff', max_length=7, verbose_name='couleur du marqueur')),
            ],
            options={
                'verbose_name': 'type de sol',
                'verbose_name_plural': 'referentiel des types de sols',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('nom_scientifique', models.CharField(blank=True, max_length=150, verbose_name='nom scientifique')),
                ('ph_min', models.FloatField(verbose_name='pH minimal tolere')),
                ('ph_max', models.FloatField(verbose_name='pH maximal tolere')),
                ('cycle_jours', models.PositiveSmallIntegerField(verbose_name='duree du cycle (jours)')),
                ('besoin_azote', models.FloatField(help_text='Seuil utilise par le bareme de score', verbose_name='besoin en azote (mg/kg)')),
                ('besoin_phosphore', models.FloatField(default=30, verbose_name='besoin en phosphore (mg/kg)')),
                ('besoin_potassium', models.FloatField(default=100, verbose_name='besoin en potassium (mg/kg)')),
                ('description', models.TextField(blank=True, verbose_name='conseils culturaux')),
                ('sols_favorables', models.ManyToManyField(blank=True, related_name='cultures_favorables', to='referentiel.typesol', verbose_name='types de sols favorables')),
            ],
            options={
                'verbose_name': 'culture',
                'verbose_name_plural': 'referentiel des cultures',
                'ordering': ['nom'],
            },
        ),
    ]
