# Generated by Django 5.0.9 on 2026-08-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='code',
            field=models.SlugField(default='', help_text="Etiquette anglaise du jeu de donnees Kaggle (ex. 'cotton'), utilisee pour relier la prediction brute du modele a cette fiche.", max_length=40, unique=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='culture',
            name='couleur_hex',
            field=models.CharField(default='#22c55e', max_length=7, verbose_name='couleur du marqueur'),
        ),
    ]
