# Generated by Django 5.0.9 on 2026-08-29 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom de la parcelle')),
                ('superficie_ha', models.FloatField(blank=True, null=True, verbose_name='superficie (hectares)')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('localite', models.CharField(blank=True, max_length=100, verbose_name='localite')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'parcelle',
                'verbose_name_plural': 'parcelles',
                'ordering': ['-date_creation'],
            },
        ),
    ]
