# Generated by Django 5.0.9 on 2026-08-29 16:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse electronique')),
                ('nom_complet', models.CharField(max_length=150, verbose_name='nom complet')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='telephone')),
                ('role', models.CharField(choices=[('agriculteur', 'Agriculteur'), ('agent', 'Agent Vulgarisateur'), ('expert', 'Expert Pedologue'), ('admin', 'Administrateur')], default='agriculteur', max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=False, verbose_name='actif')),
                ('est_banni', models.BooleanField(default=False, verbose_name='banni')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acces admin Django')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'inscription")),
                ('tentatives_echouees', models.PositiveSmallIntegerField(default=0)),
                ('verrouille_jusqu_a', models.DateTimeField(blank=True, null=True)),
                ('agent_vulgarisateur', models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producteurs_suivis', to=settings.AUTH_USER_MODEL, verbose_name='agent vulgarisateur rattache')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "entree du journal d'activite",
                'verbose_name_plural': "journal d'activite",
                'ordering': ['-horodatage'],
            },
        ),
    ]
