# Generated by Django 5.0.9 on 2026-10-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='localite',
            field=models.CharField(blank=True, max_length=100, verbose_name="localite / zone d'intervention"),
        ),
    ]
