# Generated by Django 5.0.9 on 2026-10-01 22:09

import comptes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_utilisateur_localite'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='document_justificatif',
            field=models.FileField(blank=True, null=True, upload_to=comptes.models.chemin_document_justificatif, verbose_name='document justificatif'),
        ),
    ]
